// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyzEzM-Bb2EhM2vGjgkZUl4ktScnwidFs',
    appId: '1:317666399240:web:37a75f61a53cb1acb02dbd',
    messagingSenderId: '317666399240',
    projectId: 'battery-monitoring-79ff7',
    authDomain: 'battery-monitoring-79ff7.firebaseapp.com',
    databaseURL: 'https://battery-monitoring-79ff7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'battery-monitoring-79ff7.firebasestorage.app',
    measurementId: 'G-F20B92XZG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-VKCxP63zbsY7SzQLwCEF-hPntUSwik4',
    appId: '1:317666399240:android:c8111408f3e8688cb02dbd',
    messagingSenderId: '317666399240',
    projectId: 'battery-monitoring-79ff7',
    databaseURL: 'https://battery-monitoring-79ff7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'battery-monitoring-79ff7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqvC57bBkPaa8kfunse8SrrMA5aJeAOXU',
    appId: '1:317666399240:ios:d6f256a295f37e99b02dbd',
    messagingSenderId: '317666399240',
    projectId: 'battery-monitoring-79ff7',
    databaseURL: 'https://battery-monitoring-79ff7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'battery-monitoring-79ff7.firebasestorage.app',
    iosBundleId: 'com.example.batteryMonitoring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqvC57bBkPaa8kfunse8SrrMA5aJeAOXU',
    appId: '1:317666399240:ios:d6f256a295f37e99b02dbd',
    messagingSenderId: '317666399240',
    projectId: 'battery-monitoring-79ff7',
    databaseURL: 'https://battery-monitoring-79ff7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'battery-monitoring-79ff7.firebasestorage.app',
    iosBundleId: 'com.example.batteryMonitoring',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyzEzM-Bb2EhM2vGjgkZUl4ktScnwidFs',
    appId: '1:317666399240:web:5e214dc5bf45bdb9b02dbd',
    messagingSenderId: '317666399240',
    projectId: 'battery-monitoring-79ff7',
    authDomain: 'battery-monitoring-79ff7.firebaseapp.com',
    databaseURL: 'https://battery-monitoring-79ff7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'battery-monitoring-79ff7.firebasestorage.app',
    measurementId: 'G-SYZB023J8X',
  );
}
